win,fs: Fix compiler warnings and errors
* Use `DWORD` instead of `mode_t` on Windows. It's not needed to use `mode_t` here, and it just confuses VS.

* Define `S_IRWXU` and others if not already defined.

* When compiling on my windows testing box, I get the error:

```
error: initialization of 'SECURITY_INFORMATION' {aka 'long unsigned int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
 2317 |   SECURITY_INFORMATION si = NULL;
```